# permissions for end users to view groupdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupdeployment-viewer-role
rules:
- apiGroups:
  - apps.example
  resources:
  - groupdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.example
  resources:
  - groupdeployments/status
  verbs:
  - get
