# permissions for end users to edit groupdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: groupdeployment-editor-role
rules:
- apiGroups:
  - apps.example
  resources:
  - groupdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.example
  resources:
  - groupdeployments/status
  verbs:
  - get
